project:
  type: website
  output-dir: docs

website:
  title: "teito7000"
  navbar:
    left:
      # Remove home page
      # - href: index.qmd
        # text: Home
      - projects.qmd
      # Remove about page (for now)
      # - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



