project:
  type: website
  output-dir: docs

website:
  title: "teito7000"
  navbar:
    left:
      - href: projects.qmd
        text: Projects
      # Remove home page
      # - href: index.qmd
        # text: Home
  page-footer:
    center:
      "© 2024 Ahasan Bhuiyan"

format:
  html:
    theme: 
      - cosmo
      - custom_styles.scss
    css: styles.css
    toc: true



